spring:
  application:
    name: client0030
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 975109
feign:
  hystrix:
    enabled: true

