spring:
  application:
    name: eureka-client
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 975109
server:
  port: 9093
